services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: posyandu_app
        ports:
            - "8080:8080" # Aplikasi Laravel pada port 8080
        volumes:
            - ./:/var/www/html:delegated
            - ./app/Http/Middleware:/var/www/html/app/Http/Middleware  # Mount spesifik
        depends_on:
            - db
            - redis
        environment:
            - NODE_ENV=production
        networks:
            - posyandu_net
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 30s
            retries: 5
            start_period: 30s
            timeout: 10s

    db:
        image: postgres:13
        container_name: posyandu_db
        environment:
            POSTGRES_DB: posyandu
            POSTGRES_USER: posyandu_user
            POSTGRES_PASSWORD: password
        ports:
            - "5454:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - posyandu_net

    redis:
        image: redis:alpine
        container_name: posyandu_redis
        ports:
            - "6363:6379"
        networks:
            - posyandu_net

    nginx:
        image: nginx:alpine
        container_name: posyandu_nginx
        ports:
            - "8181:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - app
        networks:
            - posyandu_net
        command: nginx -g 'daemon off;' # Pastikan Nginx tetap berjalan di foreground

volumes:
    db_data:
        driver: local

networks:
    posyandu_net:
        driver: bridge
