services:
  - type: web
    name: kenanga-posyandu
    env: docker
    plan: free
    dockerfilepath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        value: base64:lQymp7RAPugvwnKodZn7xj9FJTie2ydqA2CZEnHb0Bc=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: posyandu-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: posyandu-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: posyandu-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: posyandu-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: lax

databases:
  - name: posyandu-db
    plan: free
    postgresVersion: "13"
